version: "3.9"

services:
  controle-financeiro:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: controle-financeiro
    ports:
      - "8080:8080"
      - "5005:5005"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
